environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '7'
platform:
  - x86
  - x64
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn
  - yarn global add node-gyp && node-gyp configure --release && node-gyp build
test_script:
  - node --version
  - npm --version
  - yarn --version
  - yarn test
matrix:
  fast_finish: true
build: off
